name: auth_inmemory
description: An in-memory implementation of the AuthClient interface.
repository: https://github.com/flutter-news-app-full-source-code/auth-inmemory
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.9.0

dependencies:
  auth_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-client.git
      ref: v1.0.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  logging: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^9.0.0
